#define BLACK_BG \e[40m
#define RED_BG \e[41m
#define GREEN_BG \e[42m
#define YELLOW_BG \e[43w
#define BLUE_BG \e[44m

const int CARD_COUNT = 15;
const int CARD_HEIGHT = 14;
char card[CARD_COUNT][CARD_COUNT] = {

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*         OO       *",
        "*       OOOO       *",
        "*     OOOOOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*     OOOOOOOOO    *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOO    OOOOO   *",
        "*         OOOOO    *",
        "*        OOOOO     *",
        "*       OOOOO      *",
        "*      OOOOO       *",
        "*    OOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOO     OOOO   *",
        "*        OOOOOO    *",
        "*        OOOOOO    *",
        "*   OOO     OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOO           *",
        "*   OOOO           *",
        "*   OOOOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*   OOOOOOOOOOO    *",
        "*    OOOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOO     *",
        "*   OOOO           *",
        "*   OOOO           *",
        "*   OOOOOOOOOO     *",
        "*   OOOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*         OOOOO    *",
        "*        OOOOO     *",
        "*       OOOOO      *",
        "*      OOOOO       *",
        "*     OOOOO        *",
        "*    OOOOO        *",
        "*   OOOOO          *",
        "*   OOOO           *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOOO   *",
        "*     OOOOOOOOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*     OOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOO    OOOOO   *",
        "*   OOO   OOOOOO   *",
        "*   OOO  OOO OOO   *",
        "*   OOO OOO  OOO   *",
        "*   OOOOOO   OOO   *",
        "*   OOOOO    OOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",
    },
    {
        "********************",
        "*                  *",
        "*        OOOO      *",
        "*       OOOOOO     *",
        "*      OOOOOOOO    *",
        "*       OOO        *",
        "*      OOOO        *",
        "*        OOOO      *",
        "*        OOO       *",
        "*    OOOOOOOO      *",
        "*     OOOOOO       *",
        "*      OOOO        *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "* +2               *",
        "*                  *",
        "*       OOOOOOOO   *",
        "*       O      O   *",
        "*   OOOOOOOO   O   *",
        "*   O   O  O   O   *",
        "*   O   O  O   O   *",
        "*   O   OOOOOOOO   *",
        "*   O      O       *",
        "*   OOOOOOOO       *",
        "*                  *",
        "*               +2 *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*    OOOOOOOOOO    *",
        "*    OO      OO    *",
        "*    O O    O O    *",
        "*    O  O  O  O    *",
        "*    O   OO   O    *",
        "*    O   OO   O    *",
        "*    O  O  O  O    *",
        "*    O O    O O    *",
        "*    OO      OO    *",
        "*    OOOOOOOOOO    *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "* +4               *",
        "*      OOOOOO      *",
        "*  OOOOOO   O      *",
        "*  O    O  OOOOOO  *",
        "*  O    O  O    O  *",
        "*  O   OOOOO    O  *",
        "*  OOOOO   O    O  *",
        "*      O   OOOOOO  *",
        "*      O    O      *",
        "*      OOOOOO      *",
        "*               +4 *",
        "********************",
    }

};
