#define RED_BG \e[41m
#define GREEN_BG \e[42m
#define YELLOW_BG \e[43w
#define BLUE_BG \e[44m

char card[][] = {

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*         OO       *",
        "*       OOOO       *",
        "*     OOOOOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*        OOO       *",
        "*     OOOOOOOOO    *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOO    OOOOO   *",
        "*         OOOOO    *",
        "*        OOOOO     *",
        "*       OOOOO      *",
        "*      OOOOO       *",
        "*    OOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOO     OOOO   *",
        "*        OOOOOO    *",
        "*        OOOOOO    *",
        "*   OOO     OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOO           *",
        "*   OOOO           *",
        "*   OOOOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*   OOOOOOOOOOO    *",
        "*    OOOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOO     *",
        "*   OOOO           *",
        "*   OOOO           *",
        "*   OOOOOOOOOO     *",
        "*   OOOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*   OOOOOOOOOOOO   *",
        "*   OOOOOOOOOOOO   *",
        "*         OOOOO    *",
        "*        OOOOO     *",
        "*       OOOOO      *",
        "*      OOOOO       *",
        "*     OOOOO        *",
        "*    OOOOO        *",
        "*   OOOOO          *",
        "*   OOOO           *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOOO    OOOO   *",
        "*   OOOO    OOOO   *",
        "*    OOOOOOOOOOO   *",
        "*     OOOOOOOOOO   *",
        "*           OOOO   *",
        "*           OOOO   *",
        "*     OOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*     OOOOOOOO     *",
        "*    OOOOOOOOOO    *",
        "*   OOO    OOOOO   *",
        "*   OOO   OOOOOO   *",
        "*   OOO  OOO OOO   *",
        "*   OOO OOO  OOO   *",
        "*   OOOOOO   OOO   *",
        "*   OOOOO    OOO   *",
        "*    OOOOOOOOOO    *",
        "*     OOOOOOOO     *",
        "*                  *",
        "********************",
    },
    {
        "********************",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "********************",

    },
    {
        "********************",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "********************",

    },

    {
        "********************",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "*                  *",
        "********************",
    }

};
